%% getModelData
% This function references and executes the specified process model. Data
% which is generated by the model is saved. It is expected that only one
% time series (e.g. sensor observations) are produced.

%% Related Functions

%%
% * <extract_path.html extract_path>

%% Source Code

function gendata = getModelData(path_and_name, StopTime)
%% Preparation of 'Porcessmodel.slx'

% Load 'Processmodel.slx'
pmodel = 'GenData';
load_system([pmodel '.slx']);

% Get path and name of model
[path, name] = extract_path(path_and_name);

% Add path of process model
addpath(path);

% Set process model as referenced model
set_param([pmodel '/Processmodel'], 'ModelName', name);

% Set stop time
set_param(pmodel , 'StopTime', num2str(StopTime));

%% Running the model

% Run model. By doing so a variable 'gendata' containing the timeseries is
% prouced. This will be the returned value of this funciton. 
sim(pmodel);

% Transpose generated data
if(exist('gendata','var'))
    gendata = transpose(gendata);
else
    msgID = 'getModelData:NoData';
    msg = ['No data were produced by the model ' name '. Check whether it has exactly one numerical output' ];
    baseException = MException(msgID,msg);
    throw(baseException);
    gendata = [];
end
%% Cleaning

% Close system
close_system(pmodel, false);

end

